### ISSUE TITLE
When running assembleRelease I get error "Multiple dex files define Lcom/flutter_webview_plugin/BrowserClient;"

### ISSUE THREAD

**Issue by nullp01nt3r** [dart-flitter/flutter_webview_plugin#157]
In `pubspec.yml` I have:

```
[...]
dependencies:
  flutter_webview_plugin: "^0.2.1+2"
  package_info: "^0.3.2"
  flutter_facebook_login: "^1.1.1"
  meta: "^1.1.5"
  flutter_redux: "^0.5.0"
  google_sign_in: "^3.0.3+1"
  http: '>=0.11.1 <0.12.0'
  redux: "^3.0.0"
  redux_persist_flutter: '0.6.0-rc.1'
  uuid: "^1.0.0"
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
[...]
```

When I run `assembleRelease` I get the error:

```
[...]
:app:transformDexWithDexForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/flutter_webview_plugin/BrowserClient;
[...]
BUILD FAILED in 1m 5s
191 actionable tasks: 170 executed, 21 up-to-date
Multiple dex files define Lcom/flutter_webview_plugin/BrowserClient;
16:31:28: Tasks execution finished 'clean assembleRelease'.
```

I am using Flutter "master" (commit `e5432a2843bd6c5eefc3d6c0d48ec3155bd53969`).

Is it a possible bug, or some misconfiguration on my side?

Disclaimer: I am not an experienced Android developer, and I do not (yet) know what is a "dex" file.
