### ISSUE TITLE
uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by AhmedKhattab95** [dart-flitter/flutter_webview_plugin#944]
The plugin `flutter_webview_plugin` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
[
![image](https://user-images.githubusercontent.com/17656876/155544881-78abc88b-0012-43b5-93b5-8f5ab81b5daa.png)
](url)

**Comment by Bhat015** [comment]
Any update on this issue?

**Comment by tsepulvedacaroca01** [comment]
there is a pull [request](https://github.com/fluttercommunity/flutter_webview_plugin/pull/943) that fixes this problem, just replace flutter_webview_plugin: XXXX with:

```yml
flutter_webview_plugin:
    git:
      url: https://github.com/jiankian/flutter_webview_plugin
      ref: master
```

this solution is thanks to @[jiankian](https://github.com/jiankian)
