### ISSUE TITLE
在安卓13中报错，注释掉这个就可以了。

### ISSUE THREAD

**Issue by suchengdong** [dart-flitter/flutter_webview_plugin#951]
![image](https://user-images.githubusercontent.com/9264742/175757034-49286edc-94b8-4fec-bd13-3ca5251000b6.png)

**Comment by AbbasJafariTrax** [comment]
Did you find any solution?

**Comment by AbbasJafariTrax** [comment]
This one work for me

```

flutter_webview_plugin:
    git:
      url: https://github.com/Bhagat8533/flutter_webview_plugin # Repo
      ref: master  # Branch name
```

[Source](https://github.com/fluttercommunity/flutter_webview_plugin/issues/940#issuecomment-1186431094)
